name: "map_to_genome"
description: |
  Preprocess fastq files and align seqeuence reads to a reference genome.
keywords:
  - fasta
  - index
  - bwamem
  - samtools
  - sambamba
  - gatk4
components:
  - bwa/mem
  - samtools/sort|stats|convert
  - gatk4/baserecalibrator
input:
  - samples:
      type: map
      description: |
        Groovy Map containing sample and reads information.
        e.g. [ id: 'sample1'], [read1, read2] ]
output:
  - meta:
      type: map
      description: |
        Groovy Map containing genome reference information
        e.g. [ id:'sample1' ]
  - bam:
      type: path
      description: path for bam file
  - bai:
      type: index file
      description: samtools index for a bam file
  - cram:
      type: path
      description: path for cram file
  - crai:
      type: index file
      description: samtools index for a cram file
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"
