name: gatk4_baserecalibrator
description: Generate recalibration table for Base Quality Score Recalibration (BQSR)
keywords:
  - base quality score recalibration
  - table
  - bqsr
  - gatk4
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["Apache-2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam_file:
      type: file
      description: BAM file from alignment
      pattern: "*.bam"
  - intervals:
      type: file
      description: Bed file with the genomic regions included in the library (optional)
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - snp_known_sites:
      type: file
      description: VCF files with known sites for snps (optional)
      pattern: "*.vcf.gz"
  - snp_known_sites_tbi:
      type: file
      description: Tabix index of the known sites for snps (optional)
      pattern: "*.vcf.gz.tbi"
  - indel_known_sites:
      type: file
      description: VCF files with known sites for indels (optional)
      pattern: "*.vcf.gz"
  - indel_known_sites_tbi:
      type: file
      description: Tabix index of the known sites for indels (optional)
      pattern: "*.vcf.gz.tbi"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - table:
      type: file
      description: Recalibration table from BaseRecalibrator
      Structure: [ val(meta), path(*.table) ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kelseyz"
  - "@yocra3"
  - "@FriederikeHanssen"
  - "@maxulysse"
maintainers:
  - "@kelseyz"
  - "@yocra3"
  - "@FriederikeHanssen"
  - "@maxulysse"