name: "snv_mutect2"
description: |
  Generate filtered and normalized vcf file called by GATK4 mutect2.
  Please note, this workflow requires input CHANNELS. Input values will cause errors
keywords:
  - fasta
  - gatk4
  - bcftools
components:
  - gatk4/mutect2
  - gatk4/getpileupsummaries
  - gatk4/calculatecontamination
  - gatk4/filtermutectcalls
  - bcftools/norm
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test']
  - bam_tumor:
      type: list
      description: list of BAM files, also able to take CRAM as an input
      pattern: "*.{bam/cram}"
  - bam_normal:
      type: list
      description: list of BAM file indexes, also able to take CRAM indexes as an input
      pattern: "*.{bam/cram}"
  - bai_tumor:
      type: list
      description: list of BAM index files, also able to take CRAM as an input
      pattern: "*.{bai/crai}"
  - bai_normal:
      type: list
      description: list of BAM index file indexes, also able to take CRAM indexes as an input
      pattern: "*.{bai/crai}"
  - fasta:
      type: file
      description: The reference fasta file
      Structure: [ val(meta2), path(*.fasta) ]
  - fai:
      type: file
      description: Index of reference fasta file
      Structure: [ val(meta2), path(*.fai) ]
  - dict:
      type: file
      description: GATK sequence dictionary
      Structure: [ val(meta2), path(*.dict) ]
  - intervals:
      type: file
      description: Specify region the tools is run on.
      pattern: ".{bed,interval_list}"
  - bed_files:
      type: list
      description: Specify region the tools is run on.
      pattern: "*.{bed, interval_list}"
  - germline_resource:
      type: file
      description: Population vcf of germline sequencing, containing allele fractions.
      pattern: "*.vcf.gz"
  - germline_resource_tbi:
      type: file
      description: Index file for the germline resource.
      pattern: "*.vcf.gz.tbi"
  - pileup_variants:
      type: file
      description: Population vcf of pileup variants.
      pattern: "*.vcf.gz"
  - pileup_variants_tbi:
      type: file
      description: Index file for the pileup variants.
      pattern: "*.vcf.gz.tbi"
output:
  - vcf:
      type: file
      description: compressed filted normalized vcf file
      pattern: "*.vcf.gz"
  - tbi:
      type: file
      description: Index of vcf file
      pattern: "*vcf.gz.tbi"
  - stats:
      type: file
      description: Stats file that pairs with output vcf file
      pattern: "*vcf.gz.stats"
  - f1r2:
      type: file
      description: file containing information to be passed to LearnReadOrientationModel (only outputted when tumor_normal_pair mode is run)
      pattern: "*.f1r2.tar.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"