name: fastq_align_markdup_stats
description: Align reads to a reference genome using bwa then deduplicate with sambamba
keywords:
  - align
  - fasta
  - genome
  - reference
components:
  - bwa/mem
  - sambamba/sort
  - sambamba/markdup
  - sambamba/flagstat
  - samtools/sort
  - samtools/index
input:
  - ch_reads:
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
        Structure: [ val(meta), [ path(reads) ] ]
  - ch_index:
      type: path
      description: |
        path to bwa index files for the reference fasta file.
        Structure: [ val(meta), path(bwa_index) ]
  - ch_fasta:
      type: file
      description: |
        Optional reference fasta file. This only needs to be given if val_sort_bam = true.
        Structure: [ val(meta), path(fasta) ]
  - val_sort_bam:
      type: boolean
      description: If true bwa modules sort resulting bam files
      pattern: "true|false"
output:
  - bam:
      description: |
        BAM file produced by bwa, de-duplicated with sambamba, and sorted by samtools
        Structure: [ val(meta), path(bam) ]
  - bai:
      description: |
        BAI index of the deduplicated and sorted BAM file
        Structure: [ val(meta), path(bai) ]
  - flagstat:
      description: |
        File containing sambamba flagstat output
        Structure: [ val(meta), path(flagstat) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"