name: "bam_recalibration"
description: Base Quality Score Recalibration (BQSR) with GATK4
keywords:
  - BQSR
  - bam
  - cram
components:
  - gatk4/baserecalibrator
  - gatk4/applybqsr
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat
  - bam_stats_samtools
input:
  - ch_bam_bai:
      description: |
        Sequence alignments in BAM/BAI format
        Structure: [ val(meta), path(bam) ]
  - ch_fasta:
      description: |
        Reference genome fasta file required for BQSR
        Structure: [ path(fasta) ]
  - ch_fai:
      description: |
        Index of the reference genome fasta file
        Structure: [ path(fai) ]
  - ch_dict:
      description: |
        Sequence dictionary of the reference genome fasta file
        Structure: [ path(dict) ]
output:
  - bam:
      description: |
        processed BAM/BAI file
        Structure: [ val(meta), path(bam) ]
  - bai:
      description: |
        BAM samtools index
        Structure: [ val(meta), path(bai) ]
  - cram:
      description: |
        processed CRAM file
        Structure: [ val(meta), path(cram) ]
  - crai:
      description: |
        CRAM samtools index
        Structure: [ val(meta), path(crai) ]
  - csi:
      description: |
        CSI samtools index
        Structure: [ val(meta), path(csi) ]
  - stats:
      description: |
        File containing samtools stats output
        Structure: [ val(meta), path(stats) ]
  - flagstat:
      description: |
        File containing samtools flagstat output
        Structure: [ val(meta), path(flagstat) ]
  - idxstats:
      description: |
        File containing samtools idxstats output
        Structure: [ val(meta), path(idxstats) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@kelseyz"
maintainers:
  - "@kelseyz"